name: inha_cfg_scale2.0
group: inha_cfg_scale2.0

num_batches: 64

model_config_file: configs/train/inha_lora_finetune.yaml
act_cond_unet_checkpoint: ../checkpoints/lora_finetuned.ckpt

ddim_kwargs:
  ddim_steps: 50
  unconditional_guidance_scale: 2.0
  timestep_spacing: uniform_trailing
  guidance_rescale: 0.7
  ddim_eta: 1.0
  verbose: True

data:
  target: ldwma.lightning.data_modules.lerobot_so100.SO100DataModule
  params:
    root: ../../data/eval
    remote: False
    dataset_paths: auto
    action_stats_path: ../../data/eval/eval_action_statistics.json
    normalize_actions: True
    eval_all_episodes: True
    batch_size: 1
    num_workers: 4
    pin_memory: True
    target_height: 320
    target_width: 512
    pad: True
    camera_key: observation.images.top
    traj_len: 16
    val_fraction: 0.05
    downsample: 1
    use_language: False
